repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: forbid-submodules
      - id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
      - id: black
        args: ["--check"]

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.4
    hooks:
      - id: clang-format
