/* This file was autogenerated on 2023-06-11T16:58 DO NOT EDIT! */

#pragma once

#include <array>
#include <utility>

namespace pade {
template <auto M, auto N, auto order>
inline constexpr auto approximant(double* ys, double x, size_t offset) -> void;

template <auto M, auto N, auto... indices>
inline constexpr auto
compute_approximants(std::index_sequence<indices...>, double* ys, double x, size_t offset) -> void
{
    (approximant<M, N, indices + 1>(ys, x, offset), ...);
}
}  // namespace pade

#include "approximants/Coefficients_05_06.hpp"
#include "approximants/Coefficients_09_10.hpp"
#include "approximants/Coefficients_15_16.hpp"
#include "approximants/Coefficients_25_26.hpp"
