name: Build Notebook Container

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    name: Run repo2docker

    permissions:
      contents: write
      packages: write

    steps:

      - name: checkout files in repo
        uses: actions/checkout@v3

      - name: downcase repository name
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # revert to jupyterhub/repo2docker-action once this is fixed: https://github.com/jupyterhub/repo2docker-action/pull/101
      - name: update jupyter dependencies with repo2docker
        uses: wragge/repo2docker-action@master
        with:
          DOCKER_USERNAME: ${{ github.repository_owner }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
          DOCKER_REGISTRY: ghcr.io
          IMAGE_NAME: ${{ env.REPO }}
          BINDER_CACHE: true
          PUBLIC_REGISTRY_CHECK: true
